# Generated by Django 5.2 on 2025-05-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_collectionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramWatchAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('chain_type', models.CharField(choices=[('erc20', 'ERC20'), ('trc20', 'TRC20')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('chat_id', 'address', 'chain_type')},
            },
        ),
    ]
