# Generated by Django 5.2 on 2025-05-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_telegramwatchaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramwatchaddress',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.AlterField(
            model_name='telegramwatchaddress',
            name='address',
            field=models.CharField(help_text='区块链钱包地址', max_length=128),
        ),
        migrations.AlterField(
            model_name='telegramwatchaddress',
            name='chain_type',
            field=models.CharField(choices=[('erc20', 'ERC20'), ('trc20', 'TRC20')], max_length=10),
        ),
        migrations.AlterField(
            model_name='telegramwatchaddress',
            name='chat_id',
            field=models.CharField(help_text='Telegram chat_id', max_length=64),
        ),
    ]
