# Generated by Django 5.2.1 on 2025-05-11 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_created_at_telegramwatchaddress_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargelog',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.walletaddress'),
        ),
    ]
